hikey: fix build failure variable 'ret' set but not used
plat/hikey/bl1_plat_setup.c: In function 'hikey_jumper_init':
plat/hikey/bl1_plat_setup.c:171:6: error: variable 'ret' set but not used
[-Werror=unused-but-set-variable]
  int ret;
        ^
        cc1: all warnings being treated as errors

Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>