hikey: fix build issue missing gpio
./build/hikey/release/bl31/plat_pm.o: In function `hikey_system_off':
plat_pm.c:(.text.hikey_system_off+0x10): undefined reference to
`gpio_set_value'
make: *** [build/hikey/release/bl31/bl31.elf] Error 1

After appending gpio driver in platform.mk, this issue could be fixed.

Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>